#!/bin/bash


#@STCGoal Prototypes that are relevant are packaged in the distribution.
#@STCIssue They are in the wrong place. They should be in the package directory. 

pto_package_csv_list="./pto-package.csv"
package_name=$(cat package.json | grep '"name"' | cut -d '"' -f 4)
pre_script_warning="# This file is generated by pto-pre-build.sh. Do not edit it manually."

for l in $(cat $pto_package_csv_list);do 
  src_file=$(echo $l | cut -d, -f1)
  dst_file=$(echo $l | cut -d, -f2)
  dst_namespace=${dst_file%.*}
  echo "Copying $src_file to $package_name/$dst_file"
  echo "$pre_script_warning" > $package_name/$dst_file
  echo "# $(date)" >> $package_name/$dst_file
  echo "# SOURCE NAME: $src_file" >> $package_name/$dst_file
  echo "# ------------------------------------" >> $package_name/$dst_file
  cat $src_file >> $package_name/$dst_file
  echo "vi pyproject.toml"
  # Add Script line to pyproject.toml if it is not already there.
  if grep -q "$dst_namespace" pyproject.toml; then
    echo "Script line already exists in pyproject.toml"
    continue
  else 
    pyproject_script_line="$dst_namespace=\"$package_name.$dst_namespace:main\""
    echo "Adding as commented: # $pyproject_script_line to pyproject.toml"
    echo "$pyproject_script_line" >> pyproject.toml
  fi

done

