[build-system]
requires = ["setuptools>=40.8.0","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jgtml"
version = "0.0.323"
authors = [
  { name="Guillaume Isabelle", email="jgi@jgwill.com" },
]

description = "JGT Ml - Machine Learning Tools"
readme = "README.md"
keywords = ["data"]
requires-python = ">=3.7"
dependencies = [
]

