# This file is generated by pto-pre-build.sh. Do not edit it manually.
# Wed 10 Jul 2024 04:34:31 PM EDT
# SOURCE NAME: jgtml_cli-ttf-proto-01-2406181221.py
########################
 
import argparse
import pandas as pd
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from mlcliconstants import MLFCLI_DESCRIPTION,MLFCLI_EPILOG,MLFCLI_PROG_NAME
from mlclicommon import (add_patterns_arguments,
                         check_arguments)
import realityhelper

# Tracing integration with fail-safe design
try:
    from jgtcore import JGTTracer
    _has_tracing = True
except ImportError:
    _has_tracing = False

def create_app_arguments()->argparse.Namespace:
  from jgtutils import jgtcommon
  
  parser:argparse.ArgumentParser=jgtcommon.new_parser(MLFCLI_DESCRIPTION,MLFCLI_EPILOG,MLFCLI_PROG_NAME,add_exiting_quietly_flag=True)
  #parser = argparse.ArgumentParser(description="Create mlf alpha CSV file")
  parser=jgtcommon.add_patterns_arguments(parser)
  

  
  #flag mfiao
  #parser.add_argument("-mfiao", "--mfiao", action="store_true", help="Use mfiao")
  #drop_bidask
  #parser.add_argument("-dba", "--drop_bidask", action="store_true", help="Drop bidask")
  
  
  parser=jgtcommon.add_keepbidask_argument(parser)
  parser=jgtcommon.add_instrument_timeframe_arguments(parser)
  parser=jgtcommon.add_bars_amount_V2_arguments(parser)
  parser=jgtcommon.add_use_fresh_argument(parser)
  parser=jgtcommon.add_dropna_volume_argument(parser)
  
  lagging_group=parser.add_argument_group("Lagging")
  #lag_period
  lagging_group.add_argument("-lp", "--lag_period", type=int, default=1, help="Lag period")
  #total_lagging_periods
  lagging_group.add_argument("-tlp", "--total_lagging_periods", type=int, default=5, help="Total lagging periods")
  
  col_group=parser.add_argument_group("Columns Filtering")
  #columns_to_keep
  col_group.add_argument("-ctk", "--columns_to_keep", nargs='+', help="List of selected columns to keep", default=None)
  #columns_to_drop
  col_group.add_argument("-ctd", "--columns_to_drop", nargs='+', help="List of selected columns to drop", default=None)
  
  
  args:argparse.Namespace=jgtcommon.parse_args(parser)
  
  args =check_arguments(args)

  return args


def generate_mlf_for_pattern(
    instrument,
    timeframe,
    patternname="ttf",
    lag_period=1,
    total_lagging_periods=5,
    use_full=True,
    use_fresh=False,
    columns_to_keep=None,
    columns_to_drop=None,
    drop_bid_ask=False,
    args=None,
):
    """Convenience wrapper around realityhelper.generate_mlf_feature_pattern."""
    # Initialize tracing for programmatic MLF generation
    tracer = None
    if _has_tracing:
        try:
            tracer = JGTTracer("jgtml", "mlf_generation")
        except Exception:
            pass  # Graceful fallback
    
    if tracer:
        trace_metadata = {
            "instrument": instrument,
            "timeframe": timeframe,
            "pattern": patternname,
            "lag_period": lag_period,
            "total_lagging_periods": total_lagging_periods,
            "use_full": use_full,
            "use_fresh": use_fresh,
            "columns_to_keep": columns_to_keep,
            "columns_to_drop": columns_to_drop,
            "drop_bid_ask": drop_bid_ask,
            "programmatic_call": True
        }
        
        with tracer.trace_operation(f"MLF_prog_{instrument}_{timeframe}_{patternname}", trace_metadata) as trace_id:
            tracer.add_step("mlf_parameters", input_data=trace_metadata)
            
            # Core MLF processing
            result = realityhelper.generate_mlf_feature_pattern(
                instrument,
                timeframe,
                lag_period=lag_period,
                total_lagging_periods=total_lagging_periods,
                dropna=True,
                use_full=use_full,
                columns_to_keep=columns_to_keep,
                columns_to_drop=columns_to_drop,
                drop_bid_ask=drop_bid_ask,
                force_refresh=use_fresh,
                pn=patternname,
                args=args,
            )
            
            feature_count = len(result.columns) if result is not None else 0
            tracer.add_step("mlf_generation_complete", 
                          output_data={
                              "success": True, 
                              "pattern": patternname, 
                              "feature_count": feature_count,
                              "total_lag_periods": total_lagging_periods,
                              "call_type": "programmatic"
                          })
            return result
    else:
        return realityhelper.generate_mlf_feature_pattern(
            instrument,
            timeframe,
            lag_period=lag_period,
            total_lagging_periods=total_lagging_periods,
            dropna=True,
            use_full=use_full,
            columns_to_keep=columns_to_keep,
            columns_to_drop=columns_to_drop,
            drop_bid_ask=drop_bid_ask,
            force_refresh=use_fresh,
            pn=patternname,
            args=args,
        )
  


def main():
    args = create_app_arguments()
    
    # Initialize tracing for MLF CLI processing
    tracer = None
    if _has_tracing:
        try:
            tracer = JGTTracer("jgtml", "mlf_cli")
        except Exception:
            pass  # Graceful fallback
    
    force_refresh = args.fresh
    
    if tracer:
        trace_metadata = {
            "instrument": args.instrument,
            "timeframe": args.timeframe,
            "pattern": args.patternname,
            "lag_period": args.lag_period,
            "total_lagging_periods": args.total_lagging_periods,
            "use_full": args.full,
            "use_fresh": args.fresh,
            "columns_to_keep": args.columns_to_keep,
            "columns_to_drop": args.columns_to_drop,
            "drop_bid_ask": args.rmbidask,
            "cli_call": True
        }
        
        with tracer.trace_operation(f"MLF_CLI_{args.instrument}_{args.timeframe}_{args.patternname}", trace_metadata) as trace_id:
            tracer.add_step("cli_argument_parsing", input_data=vars(args))
            
            tracer.add_step("mlf_configuration",
                          input_data={
                              "lag_configuration": f"{args.lag_period}x{args.total_lagging_periods}",
                              "column_filtering": {
                                  "keep": args.columns_to_keep,
                                  "drop": args.columns_to_drop
                              },
                              "force_refresh": force_refresh
                          })
            
            try:
                df = run_mlf_wrapper_with_tracing(args, force_refresh, tracer)
                
                feature_count = len(df.columns) if df is not None else 0
                tracer.add_step("mlf_processing_complete",
                              output_data={
                                  "success": True,
                                  "pattern": args.patternname,
                                  "feature_count": feature_count,
                                  "instrument": args.instrument,
                                  "timeframe": args.timeframe,
                                  "call_type": "cli"
                              })
            except Exception as e:
                tracer.add_step("mlf_processing_error",
                              input_data={"error_type": type(e).__name__},
                              output_data={"error_message": str(e)})
                
                # Try fallback with TTF generation
                tracer.add_step("attempting_ttf_fallback",
                              input_data={"reason": "MLF generation failed"})
                
                import traceback
                traceback.print_exc()
                print("----WE ARE TRYING IT USING jgtapp---------")
                from jgtapp import ttf
                try:
                    ttf(
                        args.instrument,
                        args.timeframe,
                        pn=args.patternname,
                        use_fresh=args.fresh,
                        use_full=args.full,
                    )
                    tracer.add_step("ttf_fallback_complete",
                                  output_data={"ttf_generated": True})
                    
                    print("---Running MLF now that we should have the desired pattern.")
                    df = run_mlf_wrapper_with_tracing(args, force_refresh, tracer)
                    
                    feature_count = len(df.columns) if df is not None else 0
                    tracer.add_step("mlf_fallback_success",
                                  output_data={
                                      "success": True,
                                      "feature_count": feature_count,
                                      "used_fallback": True
                                  })
                except Exception as e_ttf:
                    tracer.add_step("ttf_fallback_error",
                                  input_data={"ttf_error_type": type(e_ttf).__name__},
                                  output_data={"ttf_error_message": str(e_ttf)})
                    print("Error while running ttf:", e_ttf)
                    traceback.print_exc()
                    raise
    else:
        # Original processing without tracing
        try:
            df = run_mlf_wrapper(args, force_refresh)
        except Exception as e:
            print("Error in generate_mlf_feature_pattern:", e)
            import traceback
            traceback.print_exc()
            print("----WE ARE TRYING IT USING jgtapp---------")
            from jgtapp import ttf
            try:
                ttf(
                    args.instrument,
                    args.timeframe,
                    pn=args.patternname,
                    use_fresh=args.fresh,
                    use_full=args.full,
                )
                print("---Running MLF now that we should have the desired pattern.")
                df = run_mlf_wrapper(args, force_refresh)
            except Exception as e_ttf:
                print("Error while running ttf:", e_ttf)
                traceback.print_exc()

def run_mlf_wrapper_with_tracing(args, force_refresh, tracer):
    """MLF wrapper with detailed tracing support"""
    if tracer:
        tracer.add_step("mlf_wrapper_start",
                      input_data={
                          "realityhelper_call": True,
                          "force_refresh": force_refresh
                      })
    
    df = realityhelper.generate_mlf_feature_pattern(
        args.instrument,
        args.timeframe,
        use_full=args.full,
        force_refresh=force_refresh,
        lag_period=args.lag_period,
        total_lagging_periods=args.total_lagging_periods,
        dropna=True,
        columns_to_keep=args.columns_to_keep,
        columns_to_drop=args.columns_to_drop,
        drop_bid_ask=args.rmbidask,
        pn=args.patternname,
        args=args
    )
    
    if tracer:
        feature_count = len(df.columns) if df is not None else 0
        tracer.add_step("mlf_wrapper_complete",
                      output_data={
                          "feature_count": feature_count,
                          "dataframe_shape": str(df.shape) if df is not None else "None"
                      })
    
    return df

def run_mlf_wrapper(args, force_refresh):
    """Original MLF wrapper without tracing"""
    df = realityhelper.generate_mlf_feature_pattern(
        args.instrument,
        args.timeframe,
        use_full=args.full,
        force_refresh=force_refresh,
        lag_period=args.lag_period,
        total_lagging_periods=args.total_lagging_periods,
        dropna=True,
        columns_to_keep=args.columns_to_keep,
        columns_to_drop=args.columns_to_drop,
        drop_bid_ask=args.rmbidask,
        pn=args.patternname,
        args=args
    )
    return df

if __name__ == "__main__":
  main()
  