# This file is generated by pto-pre-build.sh. Do not edit it manually.
# Wed 10 Jul 2024 04:34:31 PM EDT
# SOURCE NAME: jgtml_cli-ttf-proto-01-2406181221.py
########################
 
import argparse
import pandas as pd
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from mlcliconstants import MLFCLI_DESCRIPTION,MLFCLI_EPILOG,MLFCLI_PROG_NAME
from mlclicommon import (add_patterns_arguments,
                         check_arguments)
import realityhelper

# Tracing integration with fail-safe design
try:
    from jgtcore import JGTTracer
    _has_tracing = True
except ImportError:
    _has_tracing = False

def create_app_arguments()->argparse.Namespace:
  from jgtutils import jgtcommon
  
  parser:argparse.ArgumentParser=jgtcommon.new_parser(MLFCLI_DESCRIPTION,MLFCLI_EPILOG,MLFCLI_PROG_NAME,add_exiting_quietly_flag=True)
  #parser = argparse.ArgumentParser(description="Create mlf alpha CSV file")
  parser=jgtcommon.add_patterns_arguments(parser)
  

  
  #flag mfiao
  #parser.add_argument("-mfiao", "--mfiao", action="store_true", help="Use mfiao")
  #drop_bidask
  #parser.add_argument("-dba", "--drop_bidask", action="store_true", help="Drop bidask")
  
  
  parser=jgtcommon.add_keepbidask_argument(parser)
  parser=jgtcommon.add_instrument_timeframe_arguments(parser)
  parser=jgtcommon.add_bars_amount_V2_arguments(parser)
  parser=jgtcommon.add_use_fresh_argument(parser)
  parser=jgtcommon.add_dropna_volume_argument(parser)
  
  lagging_group=parser.add_argument_group("Lagging")
  #lag_period
  lagging_group.add_argument("-lp", "--lag_period", type=int, default=1, help="Lag period")
  #total_lagging_periods
  lagging_group.add_argument("-tlp", "--total_lagging_periods", type=int, default=5, help="Total lagging periods")
  
  col_group=parser.add_argument_group("Columns Filtering")
  #columns_to_keep
  col_group.add_argument("-ctk", "--columns_to_keep", nargs='+', help="List of selected columns to keep", default=None)
  #columns_to_drop
  col_group.add_argument("-ctd", "--columns_to_drop", nargs='+', help="List of selected columns to drop", default=None)
  
  
  args:argparse.Namespace=jgtcommon.parse_args(parser)
  
  args =check_arguments(args)

  return args


def generate_mlf_for_pattern(
    instrument,
    timeframe,
    patternname="ttf",
    lag_period=1,
    total_lagging_periods=5,
    use_full=True,
    use_fresh=False,
    columns_to_keep=None,
    columns_to_drop=None,
    drop_bid_ask=False,
    args=None,
):
    """Convenience wrapper around realityhelper.generate_mlf_feature_pattern."""
    # Initialize tracing for programmatic MLF generation
    tracer = None
    if _has_tracing:
        try:
            tracer = JGTTracer("jgtml", "mlf_generation")
        except Exception:
            pass  # Graceful fallback
    
    if tracer:
        trace_metadata = {
            "instrument": instrument,
            "timeframe": timeframe,
            "pattern": patternname,
            "lag_period": lag_period,
            "total_lagging_periods": total_lagging_periods,
            "use_full": use_full,
            "use_fresh": use_fresh,
            "columns_to_keep": columns_to_keep,
            "columns_to_drop": columns_to_drop,
            "drop_bid_ask": drop_bid_ask,
            "programmatic_call": True
        }
        
        with tracer.trace_operation(f"MLF_prog_{instrument}_{timeframe}_{patternname}", trace_metadata) as trace_id:
            tracer.add_step("mlf_parameters", input_data=trace_metadata)
            
            # Core MLF processing
            result = realityhelper.generate_mlf_feature_pattern(
                instrument,
                timeframe,
                lag_period=lag_period,
                total_lagging_periods=total_lagging_periods,
                dropna=True,
                use_full=use_full,
                columns_to_keep=columns_to_keep,
                columns_to_drop=columns_to_drop,
                drop_bid_ask=drop_bid_ask,
                force_refresh=use_fresh,
                pn=patternname,
                args=args,
            )
            
            feature_count = len(result.columns) if result is not None else 0
            tracer.add_step("mlf_generation_complete", 
                          output_data={
                              "success": True, 
                              "pattern": patternname, 
                              "feature_count": feature_count,
                              "total_lag_periods": total_lagging_periods,
                              "call_type": "programmatic"
                          })
            return result
    else:
        return realityhelper.generate_mlf_feature_pattern(
            instrument,
            timeframe,
            lag_period=lag_period,
            total_lagging_periods=total_lagging_periods,
            dropna=True,
            use_full=use_full,
            columns_to_keep=columns_to_keep,
            columns_to_drop=columns_to_drop,
            drop_bid_ask=drop_bid_ask,
            force_refresh=use_fresh,
            pn=patternname,
            args=args,
        )
  


MLF_GENERATION_FAILED_EXIT_CODE = 74


def _outfile_for(args):
  """Where this invocation is supposed to have written, per realityhelper's own rule."""
  return realityhelper.get_mlf_outfile_fullpath(
      args.instrument, args.timeframe, args.full, args.patternname)


def _describe_output(path):
  """(ok, detail) for the file a run claims to have produced.

  Existence is not enough.  This stack has twice written a Python traceback with
  a `.csv` extension (96 bytes, `jgwill/jgtsrc#121`), so the file has to parse as
  a table with at least one row before we call the run a success.
  """
  if not os.path.exists(path):
    return False, "no file at " + path
  size = os.path.getsize(path)
  if size == 0:
    return False, "empty file at " + path
  try:
    df = pd.read_csv(path, index_col=0, nrows=5)
  except Exception as e:
    return False, f"unreadable as CSV ({size} bytes, {type(e).__name__}: {e}) at {path}"
  if len(df.columns) < 2:
    return False, f"only {len(df.columns)} column(s) -- not a feature table -- at {path}"
  with open(path) as fh:
    rows = sum(1 for _ in fh) - 1
  if rows < 1:
    return False, "header only, no rows at " + path
  return True, f"rows={rows} cols={len(df.columns)} bytes={size} -> {path}"


def _report(args, ok, detail):
  """One line per (instrument, timeframe, pattern). Machine-greppable, always printed.

  `jgtapp.py` -- the reference for how these CLIs are meant to be driven -- runs
  every one of them through `subprocess.run(..., check=True)`.  That contract only
  works if the CLI's exit code tells the truth, which is what the caller of this
  function then makes sure of.
  """
  status = "WRITTEN" if ok else "FAILED"
  print(f"MLF {status}: {args.instrument} {args.timeframe} {args.patternname} :: {detail}",
        file=sys.stdout if ok else sys.stderr, flush=True)


def main():
    args = create_app_arguments()
    failure = None

    # Initialize tracing for MLF CLI processing
    tracer = None
    if _has_tracing:
        try:
            tracer = JGTTracer("jgtml", "mlf_cli")
        except Exception:
            pass  # Graceful fallback
    
    force_refresh = args.fresh
    
    if tracer:
        trace_metadata = {
            "instrument": args.instrument,
            "timeframe": args.timeframe,
            "pattern": args.patternname,
            "lag_period": args.lag_period,
            "total_lagging_periods": args.total_lagging_periods,
            "use_full": args.full,
            "use_fresh": args.fresh,
            "columns_to_keep": args.columns_to_keep,
            "columns_to_drop": args.columns_to_drop,
            "drop_bid_ask": args.rmbidask,
            "cli_call": True
        }
        
        with tracer.trace_operation(f"MLF_CLI_{args.instrument}_{args.timeframe}_{args.patternname}", trace_metadata) as trace_id:
            tracer.add_step("cli_argument_parsing", input_data=vars(args))
            
            tracer.add_step("mlf_configuration",
                          input_data={
                              "lag_configuration": f"{args.lag_period}x{args.total_lagging_periods}",
                              "column_filtering": {
                                  "keep": args.columns_to_keep,
                                  "drop": args.columns_to_drop
                              },
                              "force_refresh": force_refresh
                          })
            
            try:
                df = run_mlf_wrapper_with_tracing(args, force_refresh, tracer)
                
                feature_count = len(df.columns) if df is not None else 0
                tracer.add_step("mlf_processing_complete",
                              output_data={
                                  "success": True,
                                  "pattern": args.patternname,
                                  "feature_count": feature_count,
                                  "instrument": args.instrument,
                                  "timeframe": args.timeframe,
                                  "call_type": "cli"
                              })
            except Exception as e:
                tracer.add_step("mlf_processing_error",
                              input_data={"error_type": type(e).__name__},
                              output_data={"error_message": str(e)})
                
                # Try fallback with TTF generation
                tracer.add_step("attempting_ttf_fallback",
                              input_data={"reason": "MLF generation failed"})
                
                import traceback
                traceback.print_exc()
                print("----WE ARE TRYING IT USING jgtapp---------")
                from jgtapp import ttf
                try:
                    ttf(
                        args.instrument,
                        args.timeframe,
                        pn=args.patternname,
                        use_fresh=args.fresh,
                        use_full=args.full,
                    )
                    tracer.add_step("ttf_fallback_complete",
                                  output_data={"ttf_generated": True})
                    
                    print("---Running MLF now that we should have the desired pattern.")
                    df = run_mlf_wrapper_with_tracing(args, force_refresh, tracer)
                    
                    feature_count = len(df.columns) if df is not None else 0
                    tracer.add_step("mlf_fallback_success",
                                  output_data={
                                      "success": True,
                                      "feature_count": feature_count,
                                      "used_fallback": True
                                  })
                except Exception as e_ttf:
                    tracer.add_step("ttf_fallback_error",
                                  input_data={"ttf_error_type": type(e_ttf).__name__},
                                  output_data={"ttf_error_message": str(e_ttf)})
                    print("Error while running ttf:", e_ttf)
                    traceback.print_exc()
                    raise
    else:
        # Original processing without tracing.
        #
        # This branch is the live one: jgtcore 0.2.5 has no JGTTracer, so the
        # `except ImportError` above sets _has_tracing False.  It used to swallow
        # every failure -- inner exception printed, `main()` falling off the end,
        # `sys.exit(None)` -> **exit 0 with nothing written**.  That is the exact
        # shape that hid `int('+-')` for as long as `*_H4_mz` MLF has existed,
        # which is to say: it never existed, and nothing said so.
        import traceback
        try:
            df = run_mlf_wrapper(args, force_refresh)
        except Exception as e:
            print("Error in generate_mlf_feature_pattern:", e)
            traceback.print_exc()
            print("----WE ARE TRYING IT USING jgtapp---------")
            from jgtapp import ttf
            try:
                ttf(
                    args.instrument,
                    args.timeframe,
                    pn=args.patternname,
                    use_fresh=args.fresh,
                    use_full=args.full,
                )
                print("---Running MLF now that we should have the desired pattern.")
                df = run_mlf_wrapper(args, force_refresh)
            except Exception as e_ttf:
                print("Error while running ttf:", e_ttf)
                traceback.print_exc()
                failure = f"{type(e).__name__}: {e} (ttf fallback also failed: "\
                          f"{type(e_ttf).__name__}: {e_ttf})"

    # Whatever path got us here, the run is only a success if a usable file
    # exists on disk. Nothing below trusts a return value or the absence of an
    # exception.
    try:
        outfile = _outfile_for(args)
    except Exception as e:
        _report(args, False, f"cannot resolve output path: {type(e).__name__}: {e}")
        sys.exit(MLF_GENERATION_FAILED_EXIT_CODE)

    ok, detail = _describe_output(outfile)
    if ok and failure:
        detail += f" (recovered after: {failure})"
    if not ok and failure:
        detail += f" | first error: {failure}"
    _report(args, ok, detail)
    if not ok:
        sys.exit(MLF_GENERATION_FAILED_EXIT_CODE)

def run_mlf_wrapper_with_tracing(args, force_refresh, tracer):
    """MLF wrapper with detailed tracing support"""
    if tracer:
        tracer.add_step("mlf_wrapper_start",
                      input_data={
                          "realityhelper_call": True,
                          "force_refresh": force_refresh
                      })
    
    df = realityhelper.generate_mlf_feature_pattern(
        args.instrument,
        args.timeframe,
        use_full=args.full,
        force_refresh=force_refresh,
        lag_period=args.lag_period,
        total_lagging_periods=args.total_lagging_periods,
        dropna=True,
        columns_to_keep=args.columns_to_keep,
        columns_to_drop=args.columns_to_drop,
        drop_bid_ask=args.rmbidask,
        pn=args.patternname,
        args=args
    )
    
    if tracer:
        feature_count = len(df.columns) if df is not None else 0
        tracer.add_step("mlf_wrapper_complete",
                      output_data={
                          "feature_count": feature_count,
                          "dataframe_shape": str(df.shape) if df is not None else "None"
                      })
    
    return df

def run_mlf_wrapper(args, force_refresh):
    """Original MLF wrapper without tracing"""
    df = realityhelper.generate_mlf_feature_pattern(
        args.instrument,
        args.timeframe,
        use_full=args.full,
        force_refresh=force_refresh,
        lag_period=args.lag_period,
        total_lagging_periods=args.total_lagging_periods,
        dropna=True,
        columns_to_keep=args.columns_to_keep,
        columns_to_drop=args.columns_to_drop,
        drop_bid_ask=args.rmbidask,
        pn=args.patternname,
        args=args
    )
    return df

if __name__ == "__main__":
  main()
  